Fixes reference links in the media type section
w3c/sparql-update pull request #30
Opened 2023-07-02 14:16 UTC by Tpt

2023-07-03 06:58 UTC, rubensworks approved these changes

2023-07-03 07:56 UTC, domel approved these changes

2023-07-03 13:05 UTC, afs approved these changes

2023-07-06 15:16 UTC, TallTed requested changes

2023-07-06 15:16 UTC, TallTed commented on spec/index.html
> +      <p>The Internet Media Type / MIME Type for the SPARQL Update Language is "<code>application/sparql-update</code>".</p>
```suggestion
      <p>The Internet Media Type (formerly known as MIME Type) for the SPARQL Update Language is "<code>application/sparql-update</code>".</p>
```

2023-07-06 16:39 UTC, merged